/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
    export interface GlobalComponents {
        AdminLayout: typeof import('./components/AdminLayout.vue')['default']
        AdminPageHeader: typeof import('./components/AdminPageHeader.vue')['default']
        ElAlert: typeof import('element-plus/es')['ElAlert']
        ElButton: typeof import('element-plus/es')['ElButton']
        ElCard: typeof import('element-plus/es')['ElCard']
        ElForm: typeof import('element-plus/es')['ElForm']
        ElFormItem: typeof import('element-plus/es')['ElFormItem']
        ElIcon: typeof import('element-plus/es')['ElIcon']
        ElInput: typeof import('element-plus/es')['ElInput']
        ElTable: typeof import('element-plus/es')['ElTable']
        ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
        ElTag: typeof import('element-plus/es')['ElTag']
        ElTooltip: typeof import('element-plus/es')['ElTooltip']
        ElUpload: typeof import('element-plus/es')['ElUpload']
        OperationFeed: typeof import('./components/OperationFeed.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
    }

    export interface GlobalDirectives {
        vLoading: typeof import('element-plus/es')['ElLoadingDirective']
    }
}
